language: node_js
node_js:
  - "6"
script:
  - yarn
  - yarn build
deploy:
    provider: pages
    skip-cleanup: true
    github-token: $REPO_TOKEN
    keep-history: true
on:
    branch: master
    after_success:
  - cd ./build
  - git init
  - git config --global user.name 'Domines'
  - git config --global user.email '719480072@qq.com'
  - git remote add . https://github.com/Domines/ant.github.io.git
  - git push -u . master
    
